#! /bin/bash

GREEN="\e[1;32m"
BROWN="\e[33m"
ENDCOLOR="\e[0m"

echo -e "
${GREEN}DevOps CLI AzEnvs${ENDCOLOR}

A preconfigured container with required CLI tools, scripts and extensions for managing Azure environments and AKS clusters.

${BROWN}CLI Tools${ENDCOLOR} include:
    az                    The Azure command line interface
    kubectl (k)           The Kubernetes command line interface
    helm                  The Helm command line interface
    istioctl (ic)         The Istio command line interface
    terraform (tf)        The Hashicorp Terraform command line interface
    k9s                   A terminal UI to interact with your Kubernetes cluster

The ${BROWN}scripts${ENDCOLOR} include:
    az-initlogin          Login to the azure subscription and cluster, configured in the INIT_ environment variables

The ${BROWN}kubectl extensions${ENDCOLOR} include:
    k ns                  Switches the default namespace to the specified environment
"
