#! /bin/bash

GREEN="\e[1;32m"
CYAN="\e[35m"
ENDCOLOR="\e[0m"

echo -e "
${GREEN}DevOps CLI AKS${ENDCOLOR}

A preconfigured container with required CLI tools, scripts and extensions for managing AKS clusters.

${CYAN}CLI Tools${ENDCOLOR} include:
    az                    The Azure command line interface
    kubectl (k)           The kubernetes command line interface
    helm                  The helm command line interface

The ${CYAN}scripts${ENDCOLOR} include:
    az-initlogin          Login to the azure subscription and cluster, configured in the INIT_ environment variables

The ${CYAN}kubectl extensions${ENDCOLOR} include:
    k ns                  Switches the default namespace to the specified environment
"
